// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZZiSJ5hEzGLmNLrROzPNTVUth7o5V678',
    appId: '1:222800508266:web:76a7888bb421b4f7d86113',
    messagingSenderId: '222800508266',
    projectId: 'attandance-management-sy-89f4a',
    authDomain: 'attandance-management-sy-89f4a.firebaseapp.com',
    storageBucket: 'attandance-management-sy-89f4a.firebasestorage.app',
    measurementId: 'G-GFS19Y6KCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgfUp3WPmZjo5pOzohBFCB7MCEiaj50-s',
    appId: '1:222800508266:android:547a6c37fbc6f38cd86113',
    messagingSenderId: '222800508266',
    projectId: 'attandance-management-sy-89f4a',
    storageBucket: 'attandance-management-sy-89f4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClkU4Av2vI2CsEfLzneP4C1BU7CXghbs8',
    appId: '1:222800508266:ios:7d72501ac32694c7d86113',
    messagingSenderId: '222800508266',
    projectId: 'attandance-management-sy-89f4a',
    storageBucket: 'attandance-management-sy-89f4a.firebasestorage.app',
    iosBundleId: 'com.example.attandanceManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClkU4Av2vI2CsEfLzneP4C1BU7CXghbs8',
    appId: '1:222800508266:ios:7d72501ac32694c7d86113',
    messagingSenderId: '222800508266',
    projectId: 'attandance-management-sy-89f4a',
    storageBucket: 'attandance-management-sy-89f4a.firebasestorage.app',
    iosBundleId: 'com.example.attandanceManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZZiSJ5hEzGLmNLrROzPNTVUth7o5V678',
    appId: '1:222800508266:web:13e8638f35377cd2d86113',
    messagingSenderId: '222800508266',
    projectId: 'attandance-management-sy-89f4a',
    authDomain: 'attandance-management-sy-89f4a.firebaseapp.com',
    storageBucket: 'attandance-management-sy-89f4a.firebasestorage.app',
    measurementId: 'G-EBG1KZVFXZ',
  );

}